// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liulei/Documents/workspace/lowcode/modou/node_modules/.pnpm/dumi@2.0.13_biqbaboplfbrettd7655fr4n2y/node_modules/dumi/theme-default/slots/HeroTitle/index.js';
